version: "2.2"

services:
  nginx:
    restart: always
    image: nginx:stable
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./nginx/logs:/var/log/nginx
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites-enabled:/etc/nginx/conf.d
      - ./acme-challenge:/var/www/acme-challenge
      - ./api.ozvm.ru:/var/www/api.ozvm.ru
      - ./ozvm.ru:/var/www/ozvm.ru
    depends_on:
      - php
    networks:
      - web

  php:
    restart: always
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./api.ozvm.ru:/var/www/api.ozvm.ru
    networks:
      - web
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'XH6RymhTQJ&P'
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - web
    ports:
      - "3306:3306"

  ozvmru:
    restart: always
    build:
      context: ./ozvm.ru
      dockerfile: Dockerfile
    container_name: ozvmru
    networks:
      - web
    environment:
      - NODE_ENV=production

networks:
  web:
    driver: bridge
