
server {
    listen 80;
    server_name api.ozvm.ru;

    location ^~ /.well-known/acme-challenge/ {
        alias /var/www/acme-challenge/.well-known/acme-challenge/;
        try_files $uri =404;
    }
    
    return 301 https://$host$request_uri;
}


server {
    listen 443 ssl;
    server_name api.ozvm.ru;

    client_max_body_size 1G;
    
    location ^~ /.well-known/acme-challenge/ {
        alias /var/www/acme-challenge/.well-known/acme-challenge/;
        try_files $uri =404;
    }

    root /var/www/api.ozvm.ru/public;
    index index.php index.html;

    ssl_certificate /etc/letsencrypt/live/api.ozvm.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/api.ozvm.ru/privkey.pem;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_pass php:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}
